steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME:latest || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
  ]
# Only tag "latest" when on master
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    '[[ "$BRANCH_NAME" == "master" ]] && docker push us.gcr.io/$PROJECT_ID/$REPO_NAME:latest || true',
  ]

images: [
  'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
]
