steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/symbol-collector:latest || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us.gcr.io/$PROJECT_ID/symbol-collector:latest',
    '-t', 'us.gcr.io/$PROJECT_ID/symbol-collector:$COMMIT_SHA',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/symbol-collector:latest',
    '--target runtime',
    '.'
  ]
# Only tag "latest" when on master
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    '[[ "$BRANCH_NAME" == "master" ]] && docker push us.gcr.io/$PROJECT_ID/symbol-collector:latest || true',
  ]
- name: "us.gcr.io/$PROJECT_ID/symbol-collector:$COMMIT_SHA"
  entrypoint: 'bash'
  args: [
    '-c',
    'ls -lah; pwd; dotnet --info; dotnet SymbolCollector.Server --smoke-test'
  ]
  id: "smoke test"

#- name: "us.gcr.io/$PROJECT_ID/symbol-collector:$COMMIT_SHA"
#  args: ['--smoke-test']
#  id: "smoke test"

images: [
  'us.gcr.io/$PROJECT_ID/symbol-collector:$COMMIT_SHA',
]
