steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:latest || true',
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:latest',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:$COMMIT_SHA',
    '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:latest',
    '--build-arg', 'SENTRY_AUTH_TOKEN=$_SYMBOL_COLLECTOR_SENTRY_AUTH_TOKEN',
    '--target', 'runtime',
    '.'
  ]

# Only tag "latest" when on main
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    '[[ "$BRANCH_NAME" == "main" ]] && docker push us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:latest || true',
  ]

- name: "us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:$COMMIT_SHA"
  # We have to do this because Cloud Build by default sets it to /workspace where it mounts the checked out code
  dir: "/app"
  args: ['--smoke-test']
  env: [
    'GoogleCloud__JsonCredentialParameters__PrivateKeyId=smoke-test',
    'GoogleCloud__JsonCredentialParameters__ClientEmail=smoke@test',
    'GoogleCloud__JsonCredentialParameters__ClientId=123',
    'GoogleCloud__JsonCredentialParameters__ProjectId=smoke-test',
    'GoogleCloud__JsonCredentialParameters__PrivateKey=smoke-test',
  ]
  id: "smoke test"

images: [
  'us-central1-docker.pkg.dev/$PROJECT_ID/symbol-collector/image:$COMMIT_SHA',
]
