# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    deploy-symbol-collector:
        environment_variables:
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
        group: symbol-collector
        lock_behavior: unlockWhenFinished
        materials:
            symbol-collector_repo:
                git: git@github.com:getsentry/symbol-collector.git
                shallow_clone: true
                branch: main
                destination: symbol-collector
        stages:
            - checks:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      checks:
                          environment_variables:
                              # Required for checkruns.
                              GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
                          timeout: 1200
                          elastic_profile_id: symbol-collector
                          tasks:
                              - script: |
                                    checks-githubactions-checkruns \
                                    getsentry/symbol-collector \
                                    ${GO_REVISION_SYMBOL_COLLECTOR_REPO} \
                                    macos-latest \
                                    windows-latest
                              - script: |
                                    checks-googlecloud-check-cloudbuild \
                                    sentryio \
                                    github_getsentry_symbol-collector \
                                    symbol-collector-push-to-any-branch \
                                    ${GO_REVISION_SYMBOL_COLLECTOR_REPO} \
                                    main
            - deploy:
                  fetch_materials: true
                  jobs:
                      deploy:
                          timeout: 1200
                          elastic_profile_id: symbol-collector
                          tasks:
                              - script: |
                                    /devinfra/scripts/get-cluster-credentials \
                                    && k8s-deploy \
                                    --label-selector="service=symbol-collector" \
                                    --image="us-central1-docker.pkg.dev/sentryio/symbol-collector/image:${GO_REVISION_SYMBOL_COLLECTOR_REPO}" \
                                    --container-name="symbol-collector"
