name:  Android Device Farm Symbol Collection

on:
  workflow_dispatch: # Manual trigger
#  schedule:
#    # Every 20 minutes on Saturdays and Sundays
#    - cron: '*/10 * * * 6'
#    - cron: '*/10 * * * 0'

concurrency:
  group: android-symbol-upload-device-farm
  cancel-in-progress: false

jobs:
  run-cache-job:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.200

      - name: Restore .cache folder
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache-folder-${{ runner.os }}-${{ github.workflow }}

      - name: Download the Android app if there's a new version
        env:
          GITHUB_SHA: ${{ github.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwsh ./scripts/download-latest-android-apk.ps1

      - name: Invoke Runner
        run: |
          dotnet run
            --project src/SymbolCollector.Runner/SymbolCollector.Runner.csproj
            -c Release

      - name: Save .cache folder
        uses: actions/cache@v3
        with:
          path: .cache
          key: cache-folder-${{ runner.os }}-${{ github.workflow }}
