name:  Android Device Farm Symbol Collection

on:
  workflow_dispatch: # Manual trigger
  schedule:
    # Every 10 minutes on Saturdays and Sundays
    - cron: '*/10 * * * 6'
    - cron: '*/10 * * * 0'

concurrency:
  group: android-symbol-upload-device-farm
  cancel-in-progress: false

jobs:
  run-symbol-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.200

      - name: Restore .cache folder
        uses: actions/cache@4
        with:
          path: .cache
          key: cache-folder-${{ runner.os }}-${{ github.workflow }}

      - name: Download the Android app if there's a new version
        env:
          GITHUB_SHA: ${{ github.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwsh ./scripts/download-latest-android-apk.ps1

      - name: Invoke Runner
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          dotnet run --project src/SymbolCollector.Runner/SymbolCollector.Runner.csproj -c Release

      - name: Save .cache folder
        uses: actions/cache@v4
        with:
          path: .cache
          key: cache-folder-${{ runner.os }}-${{ github.workflow }}

      - name: Upload .cache as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache-folder
          path: .cache
